### ISSUE TITLE
Trackpad help please

### ISSUE THREAD

**Issue by thaiiy** [frozenzero123/YOGA-S740#10]
Happy New Year of the Tiger!

Thanks for your EFI. I have a C940 with the same CPU.  Your EFI boots up with a black internal display but external display works. I can try and fix that later. My main problem is the trackpad not working.

I'm not sure if the trackpad is the same, in Windows it shows up as:

 I2C-HID Device on I2C Host Controller 34E9
 
 \_SB.PCI0.I2C1.TPD0 (which is the same ACPI path as yours?)
 
 Hardware ID:
 SYNA2B31
VID_06CB

I've tried a number of different EFIs online as well as different combinations of GPIO / XOSI patches and SSDTs (yours and others). Also tried VoodooRMI kext but haven't been successful. Do you have any ideas? Thanks

**Comment by frozenzero123** [comment]
you can join us:qq  chat 1071663502
<img width="325" alt="image" src="https://user-images.githubusercontent.com/52648473/152275224-d2971569-3cec-4f5a-8f2c-b171becd4a28.png">

**Comment by frozenzero123** [comment]
There are friends with c940 machines here, but I'm not sure about their progress, just know that the trackpad is definitely driving
