### ISSUE TITLE
i7版本安装Big Sur 过程中卡在还剩14分钟，直接死机了

### ISSUE THREAD

**Issue by penkt** [frozenzero123/YOGA-S740#3]
配置还是原始的i7版本，big sur 版本为11.2.3。
没有解锁CFG lock，硬盘：SAMSUNG MZVLB512HBJQ-000L2.
OC 配置如下附件，附加网盘地址：链接: https://pan.baidu.com/s/1Zu-H7g8Mc0xtGczKcEClOA 提取码: n6fn 复制这段内容后打开百度网盘手机App，操作更方便哦。麻烦大神抽空看看，为什么卡住不动了。

**Comment by frozenzero123** [comment]
首先cfg lock 不解开 未必会影响装机 第二个是你的硬盘还是pm981a 这个硬盘不好说！第三个就是efi里可能启动参数你需要添加dvmt和cdc的修复了 具体的可以参考whatevergreen的redme 。或者换个efi ，卡机的问题 我没遇到过，大概率或许是硬盘的原因，目前使用这套efi的人没有遇到过你说的问题，你试试我说的三种可能。

**Comment by penkt** [comment]
崩溃日子出来了：

**Comment by penkt** [comment]
panic(cpu 2 caller 0xffffff8005386d06): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x47 VID=0x144d DID=0xa808
. FW Revision=3L1QEXF7\n"com.apple./AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-557.60.1/Common/IONVMeController.cpp:5472
Backtrace (CPU 2), Frame : Return Address
0xffffffa0a4f0b960 : 0xffffff8002cbab4d mach_kernel : _handle_debugger_trap + 0x3dd
0xffffffa0a4f0b9b0 : 0xffffff8002dfd7e3 mach_kernel : _kdp_i386_trap + 0x143
0xffffffa0a4f0b9f0 : 0xffffff8002dede1a mach_kernel : _kernel_trap + 0x55a
0xffffffa0a4f0ba40 : 0xffffff8002c5fa2f mach_kernel : _return_from_trap + 0xff
0xffffffa0a4f0ba60 : 0xffffff8002cba3ed mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffa0a4f0bb80 : 0xffffff8002cba6d8 mach_kernel : _panic_trap_to_debugger + 0x268
0xffffffa0a4f0bbf0 : 0xffffff80034bef9a mach_kernel : _panic + 0x54
0xffffffa0a4f0bc60 : 0xffffff8005386d06 com.apple.iokit.IONVMeFamily : __ZN16IONVMeController14CommandTimeoutEP16AppleNVMeRequest.cold.1
0xffffffa0a4f0bc80 : 0xffffff800536b427 com.apple.iokit.IONVMeFamily : __ZN16IONVMeController13FatalHandlingEv + 0x1af
0xffffffa0a4f0bde0 : 0xffffff800341d385 mach_kernel : __ZN18IOTimerEventSource15timeoutSignaledEPvS0_ + 0xa5
0xffffffa0a4f0be50 : 0xffffff800341d286 mach_kernel : __ZN18IOTimerEventSource17timeoutAndReleaseEPvS0_ + 0xc6
0xffffffa0a4f0be80 : 0xffffff8002cff725 mach_kernel : _thread_call_delayed_timer + 0x4a5
0xffffffa0a4f0bef0 : 0xffffff8002d00634 mach_kernel : _thread_call_delayed_timer + 0x13b4
0xffffffa0a4f0bfa0 : 0xffffff8002c5f13e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[D5DFC80E-EF7A-3660-BE57-473E67626B44]com.apple.0xffffff8005364000-com.apple.driver.0xffffff800538dfff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[D6C13E44-3657-3F40-99E4-355DAA82202E]com.apple.0xffffff800405a000-com.apple.driver.0xffffff8004063fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[2A454117-CDAA-301F-B609-BA396742C91A]com.apple.0xffffff8004201000-com.apple.driver.0xffffff8004215fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[BF2C5E86-1E8F-3FD4-9874-7738178FA73B]com.apple.0xffffff800561f000-com.apple.driver.0xffffff8005646fff
            dependency: com.apple.iokit.IOReportFamily(47)[D3C4FAA4-8F06-3C5C-AB36-4BE632CCE051]com.apple.0xffffff8005655000-com.apple.driver.0xffffff8005657fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[B5300908-BF34-3D47-8776-FB154A6DEE4C]com.apple.0xffffff800573f000-com.apple.driver.0xffffff8005750fff

Process name corresponding to current thread: kernel_task
Boot args: -v -igfxcdc dart=0 debug=0x100 keepsyms=1 root-dmg=file:///BaseSystem/BaseSystem.dmg chunklist-security-epoch=0 -chunklist-no-rev2-dev chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20D64

Kernel version:
Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Kernel UUID: C86236B2-4976-3542-80CA-74A6B8B4BA03
KernelCache slide: 0x0000000002a00000
KernelCache base:  0xffffff8002c00000
Kernel slide:      0x0000000002a10000
Kernel text base:  0xffffff8002c10000
__HIB  text base: 0xffffff8002b00000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization
Hibernation exit count: 0

System uptime in nanoseconds: 251599305513
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000003a947cbd7e
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000016471dca62 0x0000000000000000
last started kext at 55867912980: com.apple.driver.DiskImages.CryptoEncoding	493.0.0 (addr 0xffffff7f85fc2000, size 12288)
loaded kexts:
me.kishorprins.VoodooInput	1.0.9
com.alexandred.VoodooI2CHID	1
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.8
ru.joedm.SMCSuperIO	1.1.8
com.alexandred.VoodooI2C	2.5.2
org.coolstar.VoodooGPIO	1.1
as.acidanthera.voodoo.driver.PS2Controller	2.1.8
as.vit9696.SMCProcessor	1.1.8
as.acidanthera.BrightnessKeys	1.0.1
com.alexandred.VoodooI2CServices	1
org.acidanthera.NVMeFix	1.0.4
ru.usrsse2.SMCLightSensor	1.1.8
ru.usrsse2.SMCBatteryManager	1.1.8
as.vit9696.VirtualSMC	1.1.8
org.vanilla.driver.CPUFriend	1.2.1
as.vit9696.WhateverGreen	1.4.4
as.vit9696.AppleALC	1.5.4
as.vit9696.Lilu	1.5.0
com.apple.driver.DiskImages.CryptoEncoding	493.0.0
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.AGPM	119
com.apple.driver.X86PlatformShim	1.0.0
com.apple.nke.webcontentfilter	5
com.apple.filesystems.ntfs	3.14.3
com.apple.driver.AppleGraphicsDevicePolicy	6.2.2
com.apple.AGDCPluginDisplayMetrics	6.2.2
com.apple.driver.AppleHDAHardwareConfigDriver	283.15
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleHDA	283.15
com.apple.iokit.IOBluetoothSerialManager	8.0.3d9
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleDiskImages2	1
com.apple.driver.AGDCBacklightControl	6.2.2
com.apple.driver.AppleBacklight	180.3
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.AppleIntelMCEReporter	115
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleSMCLMU	212
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleIntelICLLPGraphicsFramebuffer	16.0.1
com.apple.nvidia.NVDAStartup	16.0.0
com.apple.driver.AppleMCCSControl	1.14
com.apple.driver.DiskImages.SparseDiskImage	493.0.0
com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
com.apple.driver.DiskImages.RAMBackingStore	493.0.0
com.apple.driver.DiskImages.HTTPBackingStore	493.0.0
com.apple.driver.DiskImages.FileBackingStore	493.0.0
com.apple.iokit.SCSITaskUserClient	436.40.6
com.apple.driver.AppleTopCaseHIDEventDriver	4030.5
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.filesystems.tmpfs	1
com.apple.filesystems.hfs.kext	556.60.1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.filesystems.apfs	1677.81.1
com.apple.private.KextAudit	1.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	310
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleGraphicsControl	6.2.2
com.apple.driver.DspFuncLib	283.15
com.apple.kext.OSvKernDSPLib	529
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.AppleGPUWrangler	6.2.2
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleHDAController	283.15
com.apple.iokit.IOHDAFamily	283.15
com.apple.iokit.IOAudioFamily	300.6.1
com.apple.vecLib.kext	1.2.0
com.apple.driver.Apple16X50Serial	3.2
com.apple.iokit.IOSerialFamily	11
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IONDRVSupport	585
com.apple.iokit.IOAcceleratorFamily2	439.52
com.apple.AppleGraphicsDeviceControl	6.2.2
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.iokit.IOGraphicsFamily	585
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.DiskImages.KernelBacked	493.0.0
com.apple.driver.AppleActuatorDriver	4400.28
com.apple.driver.AppleMultitouchDriver	4400.28
com.apple.driver.AppleInputDeviceSupport	4400.35
com.apple.driver.AppleHSBluetoothDriver	4030.5
com.apple.driver.IOBluetoothHIDDriver	8.0.3d9
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.iokit.IOBluetoothHostControllerUSBTransport	8.0.3d9
com.apple.iokit.IOBluetoothHostControllerTransport	8.0.3d9
com.apple.driver.AppleBSDKextStarter	3
com.apple.iokit.IOSurface	289.3
com.apple.iokit.IOSkywalkFamily	1
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleThunderboltNHI	7.2.8
com.apple.iokit.IOThunderboltFamily	9.3.2
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.security.AppleImage4	3.0.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOTimeSyncFamily	900.11
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOBluetoothFamily	8.0.3d9
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOBluetoothPacketLogger	8.0.3d9
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	511.60.2
com.apple.iokit.IOUSBMassStorageDriver	184.40.6
com.apple.iokit.IOSCSIBlockCommandsDevice	436.40.6
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSCSIArchitectureModelFamily	436.40.6
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.kext.CoreTrust	1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.driver.watchdog	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	11.1
com.apple.kec.Libm	1

**Comment by penkt** [comment]
还是PM981A的问题

**Comment by stopyan** [comment]
联想台式机，同联想版PM981a，直接安装进度条死机、time Machine恢复二次重启后进度条死机、使用硬盘克隆工具把其他盘上的Catalina复制进981a后第一次开机正常，重启再次开机后进度条死机，加载NVMEFIX.kext与否都没用。

**Comment by frozenzero123** [comment]
> 联想台式机，同联想版PM981a，直接安装进度条死机、time Machine恢复二次重启后进度条死机、使用硬盘克隆工具把其他盘上的Catalina复制进981a后第一次开机正常，重启再次开机后进度条死机，加载NVMEFIX.kext与否都没用。

正常！pm981a 我们都是换掉它才安装的！

**Comment by stopyan** [comment]
> > 联想台式机，同联想版PM981a，直接安装进度条死机、time Machine恢复二次重启后进度条死机、使用硬盘克隆工具把其他盘上的Catalina复制进981a后第一次开机正常，重启再次开机后进度条死机，加载NVMEFIX.kext与否都没用。
> 
> 正常！pm981a 我们都是换掉它才安装的！

另目前测试有东芝BG3 西数SN550这两款无外置缓存的NVME固态会造成S3睡眠后唤醒直接系统崩溃重启，供参考.
