### ISSUE TITLE
【黑苹果】大佬们看看我这电脑能搞嘛，可以的话求个EFI+教程~

### ISSUE THREAD

**Issue by WenDaYe-SEO** [frozenzero123/YOGA-S740#5]
大佬们看看我这个配置可以装黑苹果吗？
有没有教程呀！

https://attach.52pojie.cn/forum/202104/15/173821yowcb5r56b4z4244.png

**Comment by frozenzero123** [comment]
看着没啥问题 应该能装 可以自己配一个efi
