### ISSUE TITLE
怎么修改DVMT呢？

### ISSUE THREAD

**Issue by XuanHanTan** [frozenzero123/YOGA-S740#6]
你是怎么把DVMT修改成160M的？谢谢

**Comment by frozenzero123** [comment]
[S740-DVMT-CFGLOCK.zip](https://github.com/frozenzero123/YOGA-S740/files/7271403/S740-DVMT-CFGLOCK.zip)

**Comment by XuanHanTan** [comment]
真的有效，谢谢你！
