### ISSUE TITLE
S740 15 IRH - what Should I do

### ISSUE THREAD

**Issue by AlkoKod** [frozenzero123/YOGA-S740#7]
Hello @frozenzero123 thanks for your hard work. I am curious if I can use this on my S740-15IRH with 9750H too or what should I need to change. 

Can you help me please?

**Comment by frozenzero123** [comment]
The cpu of my device is different from yours, you can ask https://github.com/SukkaW

**Comment by AlkoKod** [comment]
Thank you very much!
