### ISSUE TITLE
Regarding latest release 1.4

### ISSUE THREAD

**Issue by ychinhan** [frozenzero123/YOGA-S740#8]
Hi, good work so far, I am looking at release 1.4 and wonder if you have changed the network card from Intel AX201 to another brand? Because the readme still says it is still for a Intel AX201, so I am a little confused

I was looking at the config.plist and found some broadcom drivers, is Lenovo 1802a a broadcom network card?

你好 想问1.4的网卡》联想版 指的是什么，网卡还是因特尔AX201 的吗？联想版1802a （00jt94）指的是新的broadcom网卡吗？

谢谢你

**Comment by frozenzero123** [comment]
网卡我自己替换了dw1820a 如果你没有更换那么记得换网卡驱动 ax201的我可能是没启用或者是删掉了
“I was looking at the config.plist and found some broadcom drivers, is Lenovo 1802a a broadcom network card?” yes！还有如果你对亮度快捷键没那么高追求 可以尝试drop ecdt.aml 来实现睡眠后开盖亮屏 （因为未知原因导致二者冲突）

**Comment by ychinhan** [comment]
"还有如果你对亮度快捷键没那么高追求 可以尝试drop ecdt.aml 来实现睡眠后开盖亮屏 （因为未知原因导致二者冲突）"
“高追求”是指的是 smooth step backlight 吗？睡眠后开盖亮屏 -> 因为我的S740是有4K屏幕的，现在verbose过后就黑屏，在tonymacx86 看到有人把盖关了再开，就有显示了。不知道ecdt.aml是否会影响这个细节。

**Comment by frozenzero123** [comment]
这个我并不太清楚 但是大概率并没有效果 现在4k屏幕的设备都有一些问题 你可以尝试一下

**Comment by ychinhan** [comment]
好的👌我的4k屏幕是可以正常进入系统，但是需要跟着我上边说的步骤来用，可以说不是一个太大的问题。目前用了一个星期，一切正常。若别人有需要我的系统讯息是：
设备:Lenovo YOGA S740 14llL(Global）
显卡: Iris Plus 940 （Iris Plus G7）+ Nvidia MX250 (disabled in BIOS)
处理器: i7 1065G7
硬盘: WD Blue SN550 500gb
声卡: ALC285 和inter sst内麦
内存: 16G DDR4X Micron
BIOS: BYCN39WW (patched CFG + DVMT thanks to frozenzero123)
CFG lock: Disabled (changed)（重点！必须完成）
DVMT: 160M (changed)（重点！必须完成）
